#!/bin/bash

#SBATCH --time=48:00:00
#SBATCH -J gemoma
#SBATCH -o gemoma_output.out
#SBATCH -e gemoma_error.out
#SBATCH --partition big_memory
#SBATCH --cpus-per-task=12

source ~/.profile
source $HOME/miniforge3/etc/profile.d/conda.sh

date

#install gemoma 1.9 (latest version) with mamba
#install mamba with mambaforge=miniforge
# wget "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh"
# bash Miniforge3-$(uname)-$(uname -m).sh
#install Gemoma 1.9 with mamba
# mamba create -n gemoma -y
# conda activate gemoma
# mamba install -c conda-forge -c bioconda gemoma=1.9 -y


# conda create -n ncbi_datasets
# conda activate ncbi_datasets
# conda install -c conda-forge ncbi-datasets-cli


#download Ref genomes:
#Mt genome from NCBI
cd $HOME/genomes
conda activate ncbi_datasets
datasets download genome accession GCF_003473485.1 --include gff3,rna,cds,protein,genome,seq-report --filename Medicago_truncatula.zip
conda deactivate ncbi_datasets

#Os genome (from RAP-DB)
mkdir ~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome
wget - P ~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/ https://rapdb.dna.affrc.go.jp/download/archive/irgsp1/IRGSP-1.0_genome.fasta.gz
cd ~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/
gunzip IRGSP-1.0_genome.fasta.gz

wget - P ~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/ https://rapdb.dna.affrc.go.jp/download/archive/irgsp1/IRGSP-1.0_representative_2023-09-07.tar.gz
gunzip IRGSP-1.0_representative_2023-09-07.tar.gz
tar -xvf IRGSP-1.0_representative_2023-09-07.tar

#download other data sets
conda activate ncbi_datasets
cd $HOME/genomes
datasets download genome accession GCF_001540865.1 --include gff3,rna,cds,protein,genome,seq-report --filename Ananas_comosus.zip
datasets download genome accession GCA_028015225.1 --include gff3,rna,cds,protein,genome,seq-report --filename Carex_myosuroides.zip
datasets download genome accession GCA_019914945.1 --include gff3,rna,cds,protein,genome,seq-report --filename Typha_latifolia.zip
datasets download genome accession GCA_011114355.1 --include gff3,rna,cds,protein,genome,seq-report --filename Carex_littledalei.zip
datasets download genome accession GCA_031770325.1 --include gff3,rna,cds,protein,genome,seq-report --filename Bolboschoenus_planiculmis.zip
datasets download genome accession GCA_027725995.1 --include gff3,rna,cds,protein,genome,seq-report --filename Rhynchospora_tenuis.zip
datasets download genome accession GCA_028095005.1 --include gff3,rna,cds,protein,genome,seq-report --filename Rhynchospora_pubera.zip
datasets download genome accession GCA_027562975.1 --include gff3,rna,cds,protein,genome,seq-report --filename Rhynchospora_breviuscula.zip
datasets download genome accession GCA_030179965.1 --include gff3,rna,cds,protein,genome,seq-report --filename Cyperus_esculentus.zip
datasets download genome accession GCA_025461125.1 --include gff3,rna,cds,protein,genome,seq-report --filename Carex_kokanica.zip
datasets download genome accession GCA_024447775.1 --include gff3,rna,cds,protein,genome,seq-report --filename Carex_cristatella.zip
datasets download genome accession GCA_024447655.1 --include gff3,rna,cds,protein,genome,seq-report --filename Carex_scoparia.zip
datasets download genome accession GCA_025461045.1 --include gff3,rna,cds,protein,genome,seq-report --filename Carex_parvula.zip
datasets download genome accession GCA_027726005.1 --include gff3,rna,cds,protein,genome,seq-report --filename Juncus_effusus.zip
datasets download genome accession GCA_946800325.1 --include gff3,rna,cds,protein,genome,seq-report --filename Luzula_sylvatica.zip
datasets download genome accession GCA_024447665.1 --include gff3,rna,cds,protein,genome,seq-report --filename Juncus_inflexus.zip
datasets download genome accession GCA_002319775.1 --include gff3,rna,cds,protein,genome,seq-report --filename Fagopyrum_tataricum.zip
datasets download genome accession GCA_023091065.1 --include gff3,rna,cds,protein,genome,seq-report --filename Dianthus_caryophyllus.zip
datasets download genome accession GCF_026212465.1 --include gff3,rna,cds,protein,genome,seq-report --filename Amaranthus_tricolor.zip
datasets download genome accession GCA_029255685.2 --include gff3,rna,cds,protein,genome,seq-report --filename Silene_conica.zip
datasets download genome accession GCA_958450325.1 --include gff3,rna,cds,protein,genome,seq-report --filename Agrostemma_githago.zip
datasets download genome accession GCA_934048045.1 --include gff3,rna,cds,protein,genome,seq-report --filename Polygonum_aviculare.zip
datasets download genome accession GCA_963457585.1 --include gff3,rna,cds,protein,genome,seq-report --filename Spergularia_bocconei.zip
datasets download genome accession GCF_001683475.1 --include gff3,rna,cds,protein,genome,seq-report --filename Chenopodium_quinoa.zip
datasets download genome accession GCA_001412135.1 --include gff3,rna,cds,protein,genome,seq-report --filename Silene_latifolia_subsp._alba.zip
datasets download genome accession GCA_029990575.1 --include gff3,rna,cds,protein,genome,seq-report --filename Petunia_axillaris_subsp._axillaris.zip
datasets download genome accession GCA_029990175.1 --include gff3,rna,cds,protein,genome,seq-report --filename Petunia_secreta.zip
datasets download genome accession GCA_032274805.1 --include gff3,rna,cds,protein,genome,seq-report --filename Gypsophila_paniculata.zip
datasets download genome accession GCA_009801015.1 --include gff3,rna,cds,protein,genome,seq-report --filename Silene_noctiflora.zip
datasets download genome accession GCA_001925005.1 --include gff3,rna,cds,protein,genome,seq-report --filename Drosera_capensis.zip
datasets download genome accession GCA_018983105.1 --include gff3,rna,cds,protein,genome,seq-report --filename Silene_uniflora.zip
datasets download genome accession GCA_029747015.1 --include gff3,rna,cds,protein,genome,seq-report --filename Carnegiea_gigantea.zip
datasets download genome accession GCA_022085475.1 --include gff3,rna,cds,protein,genome,seq-report --filename Heliosperma_pusillum.zip
datasets download genome accession GCA_028566215.1 --include gff3,rna,cds,protein,genome,seq-report --filename Silene_coronaria.zip
datasets download genome accession GCF_002917755.1 --include gff3,rna,cds,protein,genome,seq-report --filename Beta_vulgaris_subsp._vulgaris.zip
datasets download genome accession GCF_002007265.1 --include gff3,rna,cds,protein,genome,seq-report --filename Spinacia_oleracea.zip
datasets download genome accession GCA_026545225.1 --include gff3,rna,cds,protein,genome,seq-report --filename Cornus_controversa.zip
datasets download genome accession GCA_008638375.1 --include gff3,rna,cds,protein,genome,seq-report --filename Nyssa_sinensis.zip
datasets download genome accession GCA_013391885.1 --include gff3,rna,cds,protein,genome,seq-report --filename Hydrangea_macrophylla.zip
datasets download genome accession GCF_030987335.1 --include gff3,rna,cds,protein,genome,seq-report --filename Cornus_florida.zip
datasets download genome accession GCA_015680905.1 --include gff3,rna,cds,protein,genome,seq-report --filename Coptis_chinensis.zip
datasets download genome accession GCA_002738505.1 --include gff3,rna,cds,protein,genome,seq-report --filename Aquilegia_coerulea.zip
datasets download genome accession GCA_013358455.1 --include gff3,rna,cds,protein,genome,seq-report --filename Thalictrum_thalictroides.zip
datasets download genome accession GCA_028566255.1 --include gff3,rna,cds,protein,genome,seq-report --filename Geranium_maculatum.zip
datasets download genome accession GCA_900128785.1 --include gff3,rna,cds,protein,genome,seq-report --filename Arabis_alpina.zip
datasets download genome accession GCA_963576765.1 --include gff3,rna,cds,protein,genome,seq-report --filename Draba_incana.zip
datasets download genome accession GCA_001974645.1 --include gff3,rna,cds,protein,genome,seq-report --filename Capsella_bursa-pastoris.zip
datasets download genome accession GCA_020283515.1 --include gff3,rna,cds,protein,genome,seq-report --filename Alliaria_petiolata.zip
datasets download genome accession GCA_014578085.1 --include gff3,rna,cds,protein,genome,seq-report --filename Cardamine_resedifolia.zip
datasets download genome accession GCA_900406315.1 --include gff3,rna,cds,protein,genome,seq-report --filename Biscutella_laevigata_subsp._laevigata.zip
datasets download genome accession GCA_900406495.1 --include gff3,rna,cds,protein,genome,seq-report --filename Sisymbrium_altissimum.zip
datasets download genome accession GCF_000001735.4 --include gff3,rna,cds,protein,genome,seq-report --filename Arabidopsis_thaliana.zip
datasets download genome accession GCA_916181665.1 --include gff3,rna,cds,protein,genome,seq-report --filename Avena_sativa.zip
datasets download genome accession GCF_018294505.1 --include gff3,rna,cds,protein,genome,seq-report --filename Triticum_aestivum.zip
datasets download genome accession GCF_904849725.1 --include gff3,rna,cds,protein,genome,seq-report --filename Hordeum_vulgare_subsp._vulgare.zip
datasets download genome accession GCF_019359855.1 --include gff3,rna,cds,protein,genome,seq-report --filename Lolium_perenne.zip
datasets download genome accession GCA_028641055.1 --include gff3,rna,cds,protein,genome,seq-report --filename Alopecurus_myosuroides.zip
datasets download genome accession GCA_026929855.1 --include gff3,rna,cds,protein,genome,seq-report --filename Poa_annua.zip
datasets download genome accession GCA_007115705.1 --include gff3,rna,cds,protein,genome,seq-report --filename Dactylis_glomerata.zip
datasets download genome accession GCF_002870075.4 --include gff3,rna,cds,protein,genome,seq-report --filename Lactuca_sativa.zip
datasets download genome accession GCF_002127325.2 --include gff3,rna,cds,protein,genome,seq-report --filename Helianthus_annuus.zip
datasets download genome accession GCA_023525715.1 --include gff3,rna,cds,protein,genome,seq-report --filename Cichorium_intybus.zip
datasets download genome accession GCA_025667525.1 --include gff3,rna,cds,protein,genome,seq-report --filename Glebionis_coronaria.zip
datasets download genome accession GCA_022545495.1 --include gff3,rna,cds,protein,genome,seq-report --filename Chrysanthemum_lavandulifolium.zip
datasets download genome accession GCA_014162995.1 --include gff3,rna,cds,protein,genome,seq-report --filename Artemisia_annua.zip
datasets download genome accession GCA_026074375.1 --include gff3,rna,cds,protein,genome,seq-report --filename Tanacetum_coccineum.zip
datasets download genome accession GCA_910822075.1 --include gff3,rna,cds,protein,genome,seq-report --filename Senecio_squalidus.zip
unzip \*.zip
rm *.zip

#Some large genomes might not ba downloaded on the first trial, just try again by re-running the command. If it still doesn't work use the dehydration/rehydration option from the ncbi package https://www.ncbi.nlm.nih.gov/datasets/docs/v2/how-tos/genomes/large-download/

# conda activate gemoma
#vs Os selected genes
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCF_001540865.1/GCF_001540865.1_ASM154086v1_genomic.fna outdir=~/gemoma/Os_Ananas_comosus selected=~/gemoma/Os_selected a=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_representative/transcripts.gff g=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_genome.fasta GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_028015225.1/GCA_028015225.1_CAF_CaMyos_1.0_genomic.fna outdir=~/gemoma/Os_Carex_myosuroides selected=~/gemoma/Os_selected a=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_representative/transcripts.gff g=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_genome.fasta GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_019914945.1/GCA_019914945.1_TyphaL0001_genomic.fna outdir=~/gemoma/Os_Typha_latifolia selected=~/gemoma/Os_selected a=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_representative/transcripts.gff g=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_genome.fasta GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_011114355.1/GCA_011114355.1_ASM1111435v1_genomic.fna outdir=~/gemoma/Os_Carex_littledalei selected=~/gemoma/Os_selected a=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_representative/transcripts.gff g=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_genome.fasta GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_031770325.1/GCA_031770325.1_CAF_BolPas_1.0_genomic.fna outdir=~/gemoma/Os_Bolboschoenus_planiculmis selected=~/gemoma/Os_selected a=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_representative/transcripts.gff g=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_genome.fasta GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_027725995.1/GCA_027725995.1_MPIPZ_rhyTen1m_1_genomic.fna outdir=~/gemoma/Os_Rhynchospora_tenuis selected=~/gemoma/Os_selected a=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_representative/transcripts.gff g=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_genome.fasta GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_028095005.1/GCA_028095005.1_MPIPZ_rhyPub2m_2.0_genomic.fna outdir=~/gemoma/Os_Rhynchospora_pubera selected=~/gemoma/Os_selected a=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_representative/transcripts.gff g=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_genome.fasta GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_027562975.1/GCA_027562975.1_MPIPZ_rhyBre1m_1.0_genomic.fna outdir=~/gemoma/Os_Rhynchospora_breviuscula selected=~/gemoma/Os_selected a=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_representative/transcripts.gff g=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_genome.fasta GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_030179965.1/GCA_030179965.1_Ces_v0.1_genomic.fna outdir=~/gemoma/Os_Cyperus_esculentus selected=~/gemoma/Os_selected a=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_representative/transcripts.gff g=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_genome.fasta GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_025461125.1/GCA_025461125.1_ASM2546112v1_genomic.fna outdir=~/gemoma/Os_Carex_kokanica selected=~/gemoma/Os_selected a=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_representative/transcripts.gff g=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_genome.fasta GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_024447775.1/GCA_024447775.1_MSU_CaCris_1.0_genomic.fna outdir=~/gemoma/Os_Carex_cristatella selected=~/gemoma/Os_selected a=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_representative/transcripts.gff g=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_genome.fasta GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_024447655.1/GCA_024447655.1_MSU_CaScop_1.0_genomic.fna outdir=~/gemoma/Os_Carex_scoparia selected=~/gemoma/Os_selected a=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_representative/transcripts.gff g=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_genome.fasta GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_025461045.1/GCA_025461045.1_ASM2546104v1_genomic.fna outdir=~/gemoma/Os_Carex_parvula selected=~/gemoma/Os_selected a=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_representative/transcripts.gff g=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_genome.fasta GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_027726005.1/GCA_027726005.1_MPIPZ_junEff1m_1_genomic.fna outdir=~/gemoma/Os_Juncus_effusus selected=~/gemoma/Os_selected a=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_representative/transcripts.gff g=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_genome.fasta GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_946800325.1/GCA_946800325.1_lpLuzSylv1.1_genomic.fna outdir=~/gemoma/Os_Luzula_sylvatica selected=~/gemoma/Os_selected a=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_representative/transcripts.gff g=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_genome.fasta GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_024447665.1/GCA_024447665.1_MSU_JuInfl_1.0_genomic.fna outdir=~/gemoma/Os_Juncus_inflexus selected=~/gemoma/Os_selected a=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_representative/transcripts.gff g=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_genome.fasta GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_002319775.1/GCA_002319775.1_Ft1.0_genomic.fna outdir=~/gemoma/Os_Fagopyrum_tataricum selected=~/gemoma/Os_selected a=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_representative/transcripts.gff g=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_genome.fasta GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_023091065.1/GCA_023091065.1_ASM2309106v1_genomic.fna outdir=~/gemoma/Os_Dianthus_caryophyllus selected=~/gemoma/Os_selected a=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_representative/transcripts.gff g=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_genome.fasta GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCF_026212465.1/GCF_026212465.1_ASM2621246v1_genomic.fna outdir=~/gemoma/Os_Amaranthus_tricolor selected=~/gemoma/Os_selected a=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_representative/transcripts.gff g=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_genome.fasta GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_029255685.2/GCA_029255685.2_ASM2925568v2_genomic.fna outdir=~/gemoma/Os_Silene_conica selected=~/gemoma/Os_selected a=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_representative/transcripts.gff g=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_genome.fasta GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_958450325.1/GCA_958450325.1_dcAgrGith1.1_genomic.fna outdir=~/gemoma/Os_Agrostemma_githago selected=~/gemoma/Os_selected a=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_representative/transcripts.gff g=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_genome.fasta GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_934048045.1/GCA_934048045.1_dcPolAvic1.1_genomic.fna outdir=~/gemoma/Os_Polygonum_aviculare selected=~/gemoma/Os_selected a=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_representative/transcripts.gff g=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_genome.fasta GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_963457585.1/GCA_963457585.1_dcSpeBocc1.1_genomic.fna outdir=~/gemoma/Os_Spergularia_bocconei selected=~/gemoma/Os_selected a=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_representative/transcripts.gff g=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_genome.fasta GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCF_001683475.1/GCF_001683475.1_ASM168347v1_genomic.fna outdir=~/gemoma/Os_Chenopodium_quinoa selected=~/gemoma/Os_selected a=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_representative/transcripts.gff g=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_genome.fasta GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_001412135.1/GCA_001412135.1_ASM141213v1_genomic.fna outdir=~/gemoma/Os_Silene_latifolia_subsp._alba selected=~/gemoma/Os_selected a=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_representative/transcripts.gff g=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_genome.fasta GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_029990575.1/GCA_029990575.1_ASM2999057v1_genomic.fna outdir=~/gemoma/Os_Petunia_axillaris_subsp._axillaris selected=~/gemoma/Os_selected a=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_representative/transcripts.gff g=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_genome.fasta GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_029990175.1/GCA_029990175.1_Psec_v2_Bern_genomic.fna outdir=~/gemoma/Os_Petunia_secreta selected=~/gemoma/Os_selected a=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_representative/transcripts.gff g=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_genome.fasta GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_032274805.1/GCA_032274805.1_ASM3227480v1_genomic.fna outdir=~/gemoma/Os_Gypsophila_paniculata selected=~/gemoma/Os_selected a=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_representative/transcripts.gff g=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_genome.fasta GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_009801015.1/GCA_009801015.1_ASM980101v1_genomic.fna outdir=~/gemoma/Os_Silene_noctiflora selected=~/gemoma/Os_selected a=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_representative/transcripts.gff g=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_genome.fasta GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_001925005.1/GCA_001925005.1_ASM192500v1_genomic.fna outdir=~/gemoma/Os_Drosera_capensis selected=~/gemoma/Os_selected a=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_representative/transcripts.gff g=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_genome.fasta GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_018983105.1/GCA_018983105.1_ASM1898310v1_genomic.fna outdir=~/gemoma/Os_Silene_uniflora selected=~/gemoma/Os_selected a=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_representative/transcripts.gff g=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_genome.fasta GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_029747015.1/GCA_029747015.1_UA_SGP5p_2_genomic.fna outdir=~/gemoma/Os_Carnegiea_gigantea selected=~/gemoma/Os_selected a=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_representative/transcripts.gff g=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_genome.fasta GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_022085475.1/GCA_022085475.1_ASM2208547v1_genomic.fna outdir=~/gemoma/Os_Heliosperma_pusillum selected=~/gemoma/Os_selected a=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_representative/transcripts.gff g=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_genome.fasta GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_028566215.1/GCA_028566215.1_ASM2856621v1_genomic.fna outdir=~/gemoma/Os_Silene_coronaria selected=~/gemoma/Os_selected a=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_representative/transcripts.gff g=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_genome.fasta GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCF_002917755.1/GCF_002917755.1_EL10_1.0_genomic.fna outdir=~/gemoma/Os_Beta_vulgaris_subsp._vulgaris selected=~/gemoma/Os_selected a=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_representative/transcripts.gff g=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_genome.fasta GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCF_002007265.1/GCF_002007265.1_ASM200726v1_genomic.fna outdir=~/gemoma/Os_Spinacia_oleracea selected=~/gemoma/Os_selected a=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_representative/transcripts.gff g=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_genome.fasta GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_026545225.1/GCA_026545225.1_ASM2654522v1_genomic.fna outdir=~/gemoma/Os_Cornus_controversa selected=~/gemoma/Os_selected a=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_representative/transcripts.gff g=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_genome.fasta GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_008638375.1/GCA_008638375.1_ASM863837v1_genomic.fna outdir=~/gemoma/Os_Nyssa_sinensis selected=~/gemoma/Os_selected a=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_representative/transcripts.gff g=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_genome.fasta GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_013391885.1/GCA_013391885.1_HMA_r1.2_0_genomic.fna outdir=~/gemoma/Os_Hydrangea_macrophylla selected=~/gemoma/Os_selected a=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_representative/transcripts.gff g=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_genome.fasta GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCF_030987335.1/GCF_030987335.1_ASM3098733v1_genomic.fna outdir=~/gemoma/Os_Cornus_florida selected=~/gemoma/Os_selected a=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_representative/transcripts.gff g=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_genome.fasta GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_015680905.1/GCA_015680905.1_ASM1568090v1_genomic.fna outdir=~/gemoma/Os_Coptis_chinensis selected=~/gemoma/Os_selected a=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_representative/transcripts.gff g=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_genome.fasta GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_002738505.1/GCA_002738505.1_Aquilegia_coerulea_v1_genomic.fna outdir=~/gemoma/Os_Aquilegia_coerulea selected=~/gemoma/Os_selected a=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_representative/transcripts.gff g=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_genome.fasta GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_013358455.1/GCA_013358455.1_MaSuRCA_all.p2_genomic.fna outdir=~/gemoma/Os_Thalictrum_thalictroides selected=~/gemoma/Os_selected a=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_representative/transcripts.gff g=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_genome.fasta GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_028566255.1/GCA_028566255.1_ASM2856625v1_genomic.fna outdir=~/gemoma/Os_Geranium_maculatum selected=~/gemoma/Os_selected a=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_representative/transcripts.gff g=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_genome.fasta GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_900128785.1/GCA_900128785.1_MPIPZ.v5_genomic.fna outdir=~/gemoma/Os_Arabis_alpina selected=~/gemoma/Os_selected a=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_representative/transcripts.gff g=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_genome.fasta GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_963576765.1/GCA_963576765.1_ddDraInca1.1_genomic.fna outdir=~/gemoma/Os_Draba_incana selected=~/gemoma/Os_selected a=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_representative/transcripts.gff g=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_genome.fasta GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_001974645.1/GCA_001974645.1_C_bursa_pastoris_nuclear_genome_v1_genomic.fna outdir=~/gemoma/Os_Capsella_bursa-pastoris selected=~/gemoma/Os_selected a=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_representative/transcripts.gff g=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_genome.fasta GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_020283515.1/GCA_020283515.1_Apet_EFCC3-3-20v4_genomic.fna outdir=~/gemoma/Os_Alliaria_petiolata selected=~/gemoma/Os_selected a=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_representative/transcripts.gff g=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_genome.fasta GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_014578085.1/GCA_014578085.1_Cresedifolia_CH_v1_genomic.fna outdir=~/gemoma/Os_Cardamine_resedifolia selected=~/gemoma/Os_selected a=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_representative/transcripts.gff g=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_genome.fasta GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_900406315.1/GCA_900406315.1_Biscutella longifolia_genomic.fna outdir=~/gemoma/Os_Biscutella_laevigata_subsp._laevigata selected=~/gemoma/Os_selected a=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_representative/transcripts.gff g=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_genome.fasta GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_900406495.1/GCA_900406495.1_ASM90040649v1_genomic.fna outdir=~/gemoma/Os_Sisymbrium_altissimum selected=~/gemoma/Os_selected a=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_representative/transcripts.gff g=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_genome.fasta GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCF_000001735.4/GCF_000001735.4_TAIR10.1_genomic.fna outdir=~/gemoma/Os_Arabidopsis_thaliana selected=~/gemoma/Os_selected a=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_representative/transcripts.gff g=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_genome.fasta GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_916181665.1/GCA_916181665.1_Oat _OT3098 _v2_genomic.fna outdir=~/gemoma/Os_Avena_sativa selected=~/gemoma/Os_selected a=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_representative/transcripts.gff g=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_genome.fasta GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCF_018294505.1/GCF_018294505.1_IWGSC CS RefSeq v2.1_genomic.fna outdir=~/gemoma/Os_Triticum_aestivum selected=~/gemoma/Os_selected a=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_representative/transcripts.gff g=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_genome.fasta GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCF_904849725.1/GCF_904849725.1_MorexV3_pseudomolecules_assembly_genomic.fna outdir=~/gemoma/Os_Hordeum_vulgare_subsp._vulgare selected=~/gemoma/Os_selected a=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_representative/transcripts.gff g=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_genome.fasta GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCF_019359855.1/GCF_019359855.1_MPB_Lper_Kyuss_1697_genomic.fna outdir=~/gemoma/Os_Lolium_perenne selected=~/gemoma/Os_selected a=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_representative/transcripts.gff g=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_genome.fasta GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_028641055.1/GCA_028641055.1_Alomy_genome_v1_genomic.fna outdir=~/gemoma/Os_Alopecurus_myosuroides selected=~/gemoma/Os_selected a=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_representative/transcripts.gff g=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_genome.fasta GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_026929855.1/GCA_026929855.1_FRR_PoAnn_1.0_genomic.fna outdir=~/gemoma/Os_Poa_annua selected=~/gemoma/Os_selected a=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_representative/transcripts.gff g=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_genome.fasta GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_007115705.1/GCA_007115705.1_ASM711570v1_genomic.fna outdir=~/gemoma/Os_Dactylis_glomerata selected=~/gemoma/Os_selected a=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_representative/transcripts.gff g=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_genome.fasta GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCF_002870075.4/GCF_002870075.4_Lsat_Salinas_v11_genomic.fna outdir=~/gemoma/Os_Lactuca_sativa selected=~/gemoma/Os_selected a=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_representative/transcripts.gff g=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_genome.fasta GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCF_002127325.2/GCF_002127325.2_HanXRQr2.0-SUNRISE_genomic.fna outdir=~/gemoma/Os_Helianthus_annuus selected=~/gemoma/Os_selected a=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_representative/transcripts.gff g=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_genome.fasta GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_023525715.1/GCA_023525715.1_ASM2352571v1_genomic.fna outdir=~/gemoma/Os_Cichorium_intybus selected=~/gemoma/Os_selected a=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_representative/transcripts.gff g=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_genome.fasta GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_025667525.1/GCA_025667525.1_Gcor_v1_genomic.fna outdir=~/gemoma/Os_Glebionis_coronaria selected=~/gemoma/Os_selected a=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_representative/transcripts.gff g=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_genome.fasta GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_022545495.1/GCA_022545495.1_ASM2254549v1_genomic.fna outdir=~/gemoma/Os_Chrysanthemum_lavandulifolium selected=~/gemoma/Os_selected a=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_representative/transcripts.gff g=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_genome.fasta GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_014162995.1/GCA_014162995.1_Aran_genomic.fna outdir=~/gemoma/Os_Artemisia_annua selected=~/gemoma/Os_selected a=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_representative/transcripts.gff g=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_genome.fasta GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_026074375.1/GCA_026074375.1_Tcoc_v1.0_genomic.fna outdir=~/gemoma/Os_Tanacetum_coccineum selected=~/gemoma/Os_selected a=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_representative/transcripts.gff g=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_genome.fasta GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_910822075.1/GCA_910822075.1_dSenSqu2.1_genomic.fna outdir=~/gemoma/Os_Senecio_squalidus selected=~/gemoma/Os_selected a=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_representative/transcripts.gff g=~/genomes/ncbi_dataset/data/Os_IRGSP-1.0_genome/IRGSP-1.0_genome.fasta GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
 
#vs Mt selected genes
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCF_001540865.1/GCF_001540865.1_ASM154086v1_genomic.fna outdir=~/gemoma/Mt_Ananas_comosus selected=~/gemoma/Mt_selected a=~/genomes/ncbi_dataset/data/GCF_003473485.1/genomic.gff g=~/genomes/ncbi_dataset/data/GCF_003473485.1/GCF_003473485.1_MtrunA17r5.0-ANR_genomic.fna GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_028015225.1/GCA_028015225.1_CAF_CaMyos_1.0_genomic.fna outdir=~/gemoma/Mt_Carex_myosuroides selected=~/gemoma/Mt_selected a=~/genomes/ncbi_dataset/data/GCF_003473485.1/genomic.gff g=~/genomes/ncbi_dataset/data/GCF_003473485.1/GCF_003473485.1_MtrunA17r5.0-ANR_genomic.fna GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_019914945.1/GCA_019914945.1_TyphaL0001_genomic.fna outdir=~/gemoma/Mt_Typha_latifolia selected=~/gemoma/Mt_selected a=~/genomes/ncbi_dataset/data/GCF_003473485.1/genomic.gff g=~/genomes/ncbi_dataset/data/GCF_003473485.1/GCF_003473485.1_MtrunA17r5.0-ANR_genomic.fna GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_011114355.1/GCA_011114355.1_ASM1111435v1_genomic.fna outdir=~/gemoma/Mt_Carex_littledalei selected=~/gemoma/Mt_selected a=~/genomes/ncbi_dataset/data/GCF_003473485.1/genomic.gff g=~/genomes/ncbi_dataset/data/GCF_003473485.1/GCF_003473485.1_MtrunA17r5.0-ANR_genomic.fna GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_031770325.1/GCA_031770325.1_CAF_BolPas_1.0_genomic.fna outdir=~/gemoma/Mt_Bolboschoenus_planiculmis selected=~/gemoma/Mt_selected a=~/genomes/ncbi_dataset/data/GCF_003473485.1/genomic.gff g=~/genomes/ncbi_dataset/data/GCF_003473485.1/GCF_003473485.1_MtrunA17r5.0-ANR_genomic.fna GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_027725995.1/GCA_027725995.1_MPIPZ_rhyTen1m_1_genomic.fna outdir=~/gemoma/Mt_Rhynchospora_tenuis selected=~/gemoma/Mt_selected a=~/genomes/ncbi_dataset/data/GCF_003473485.1/genomic.gff g=~/genomes/ncbi_dataset/data/GCF_003473485.1/GCF_003473485.1_MtrunA17r5.0-ANR_genomic.fna GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_028095005.1/GCA_028095005.1_MPIPZ_rhyPub2m_2.0_genomic.fna outdir=~/gemoma/Mt_Rhynchospora_pubera selected=~/gemoma/Mt_selected a=~/genomes/ncbi_dataset/data/GCF_003473485.1/genomic.gff g=~/genomes/ncbi_dataset/data/GCF_003473485.1/GCF_003473485.1_MtrunA17r5.0-ANR_genomic.fna GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_027562975.1/GCA_027562975.1_MPIPZ_rhyBre1m_1.0_genomic.fna outdir=~/gemoma/Mt_Rhynchospora_breviuscula selected=~/gemoma/Mt_selected a=~/genomes/ncbi_dataset/data/GCF_003473485.1/genomic.gff g=~/genomes/ncbi_dataset/data/GCF_003473485.1/GCF_003473485.1_MtrunA17r5.0-ANR_genomic.fna GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_030179965.1/GCA_030179965.1_Ces_v0.1_genomic.fna outdir=~/gemoma/Mt_Cyperus_esculentus selected=~/gemoma/Mt_selected a=~/genomes/ncbi_dataset/data/GCF_003473485.1/genomic.gff g=~/genomes/ncbi_dataset/data/GCF_003473485.1/GCF_003473485.1_MtrunA17r5.0-ANR_genomic.fna GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_025461125.1/GCA_025461125.1_ASM2546112v1_genomic.fna outdir=~/gemoma/Mt_Carex_kokanica selected=~/gemoma/Mt_selected a=~/genomes/ncbi_dataset/data/GCF_003473485.1/genomic.gff g=~/genomes/ncbi_dataset/data/GCF_003473485.1/GCF_003473485.1_MtrunA17r5.0-ANR_genomic.fna GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_024447775.1/GCA_024447775.1_MSU_CaCris_1.0_genomic.fna outdir=~/gemoma/Mt_Carex_cristatella selected=~/gemoma/Mt_selected a=~/genomes/ncbi_dataset/data/GCF_003473485.1/genomic.gff g=~/genomes/ncbi_dataset/data/GCF_003473485.1/GCF_003473485.1_MtrunA17r5.0-ANR_genomic.fna GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_024447655.1/GCA_024447655.1_MSU_CaScop_1.0_genomic.fna outdir=~/gemoma/Mt_Carex_scoparia selected=~/gemoma/Mt_selected a=~/genomes/ncbi_dataset/data/GCF_003473485.1/genomic.gff g=~/genomes/ncbi_dataset/data/GCF_003473485.1/GCF_003473485.1_MtrunA17r5.0-ANR_genomic.fna GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_025461045.1/GCA_025461045.1_ASM2546104v1_genomic.fna outdir=~/gemoma/Mt_Carex_parvula selected=~/gemoma/Mt_selected a=~/genomes/ncbi_dataset/data/GCF_003473485.1/genomic.gff g=~/genomes/ncbi_dataset/data/GCF_003473485.1/GCF_003473485.1_MtrunA17r5.0-ANR_genomic.fna GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_027726005.1/GCA_027726005.1_MPIPZ_junEff1m_1_genomic.fna outdir=~/gemoma/Mt_Juncus_effusus selected=~/gemoma/Mt_selected a=~/genomes/ncbi_dataset/data/GCF_003473485.1/genomic.gff g=~/genomes/ncbi_dataset/data/GCF_003473485.1/GCF_003473485.1_MtrunA17r5.0-ANR_genomic.fna GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_946800325.1/GCA_946800325.1_lpLuzSylv1.1_genomic.fna outdir=~/gemoma/Mt_Luzula_sylvatica selected=~/gemoma/Mt_selected a=~/genomes/ncbi_dataset/data/GCF_003473485.1/genomic.gff g=~/genomes/ncbi_dataset/data/GCF_003473485.1/GCF_003473485.1_MtrunA17r5.0-ANR_genomic.fna GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_024447665.1/GCA_024447665.1_MSU_JuInfl_1.0_genomic.fna outdir=~/gemoma/Mt_Juncus_inflexus selected=~/gemoma/Mt_selected a=~/genomes/ncbi_dataset/data/GCF_003473485.1/genomic.gff g=~/genomes/ncbi_dataset/data/GCF_003473485.1/GCF_003473485.1_MtrunA17r5.0-ANR_genomic.fna GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_002319775.1/GCA_002319775.1_Ft1.0_genomic.fna outdir=~/gemoma/Mt_Fagopyrum_tataricum selected=~/gemoma/Mt_selected a=~/genomes/ncbi_dataset/data/GCF_003473485.1/genomic.gff g=~/genomes/ncbi_dataset/data/GCF_003473485.1/GCF_003473485.1_MtrunA17r5.0-ANR_genomic.fna GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_023091065.1/GCA_023091065.1_ASM2309106v1_genomic.fna outdir=~/gemoma/Mt_Dianthus_caryophyllus selected=~/gemoma/Mt_selected a=~/genomes/ncbi_dataset/data/GCF_003473485.1/genomic.gff g=~/genomes/ncbi_dataset/data/GCF_003473485.1/GCF_003473485.1_MtrunA17r5.0-ANR_genomic.fna GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCF_026212465.1/GCF_026212465.1_ASM2621246v1_genomic.fna outdir=~/gemoma/Mt_Amaranthus_tricolor selected=~/gemoma/Mt_selected a=~/genomes/ncbi_dataset/data/GCF_003473485.1/genomic.gff g=~/genomes/ncbi_dataset/data/GCF_003473485.1/GCF_003473485.1_MtrunA17r5.0-ANR_genomic.fna GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_029255685.2/GCA_029255685.2_ASM2925568v2_genomic.fna outdir=~/gemoma/Mt_Silene_conica selected=~/gemoma/Mt_selected a=~/genomes/ncbi_dataset/data/GCF_003473485.1/genomic.gff g=~/genomes/ncbi_dataset/data/GCF_003473485.1/GCF_003473485.1_MtrunA17r5.0-ANR_genomic.fna GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_958450325.1/GCA_958450325.1_dcAgrGith1.1_genomic.fna outdir=~/gemoma/Mt_Agrostemma_githago selected=~/gemoma/Mt_selected a=~/genomes/ncbi_dataset/data/GCF_003473485.1/genomic.gff g=~/genomes/ncbi_dataset/data/GCF_003473485.1/GCF_003473485.1_MtrunA17r5.0-ANR_genomic.fna GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_934048045.1/GCA_934048045.1_dcPolAvic1.1_genomic.fna outdir=~/gemoma/Mt_Polygonum_aviculare selected=~/gemoma/Mt_selected a=~/genomes/ncbi_dataset/data/GCF_003473485.1/genomic.gff g=~/genomes/ncbi_dataset/data/GCF_003473485.1/GCF_003473485.1_MtrunA17r5.0-ANR_genomic.fna GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_963457585.1/GCA_963457585.1_dcSpeBocc1.1_genomic.fna outdir=~/gemoma/Mt_Spergularia_bocconei selected=~/gemoma/Mt_selected a=~/genomes/ncbi_dataset/data/GCF_003473485.1/genomic.gff g=~/genomes/ncbi_dataset/data/GCF_003473485.1/GCF_003473485.1_MtrunA17r5.0-ANR_genomic.fna GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCF_001683475.1/GCF_001683475.1_ASM168347v1_genomic.fna outdir=~/gemoma/Mt_Chenopodium_quinoa selected=~/gemoma/Mt_selected a=~/genomes/ncbi_dataset/data/GCF_003473485.1/genomic.gff g=~/genomes/ncbi_dataset/data/GCF_003473485.1/GCF_003473485.1_MtrunA17r5.0-ANR_genomic.fna GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_001412135.1/GCA_001412135.1_ASM141213v1_genomic.fna outdir=~/gemoma/Mt_Silene_latifolia_subsp._alba selected=~/gemoma/Mt_selected a=~/genomes/ncbi_dataset/data/GCF_003473485.1/genomic.gff g=~/genomes/ncbi_dataset/data/GCF_003473485.1/GCF_003473485.1_MtrunA17r5.0-ANR_genomic.fna GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_029990575.1/GCA_029990575.1_ASM2999057v1_genomic.fna outdir=~/gemoma/Mt_Petunia_axillaris_subsp._axillaris selected=~/gemoma/Mt_selected a=~/genomes/ncbi_dataset/data/GCF_003473485.1/genomic.gff g=~/genomes/ncbi_dataset/data/GCF_003473485.1/GCF_003473485.1_MtrunA17r5.0-ANR_genomic.fna GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_029990175.1/GCA_029990175.1_Psec_v2_Bern_genomic.fna outdir=~/gemoma/Mt_Petunia_secreta selected=~/gemoma/Mt_selected a=~/genomes/ncbi_dataset/data/GCF_003473485.1/genomic.gff g=~/genomes/ncbi_dataset/data/GCF_003473485.1/GCF_003473485.1_MtrunA17r5.0-ANR_genomic.fna GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_032274805.1/GCA_032274805.1_ASM3227480v1_genomic.fna outdir=~/gemoma/Mt_Gypsophila_paniculata selected=~/gemoma/Mt_selected a=~/genomes/ncbi_dataset/data/GCF_003473485.1/genomic.gff g=~/genomes/ncbi_dataset/data/GCF_003473485.1/GCF_003473485.1_MtrunA17r5.0-ANR_genomic.fna GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_009801015.1/GCA_009801015.1_ASM980101v1_genomic.fna outdir=~/gemoma/Mt_Silene_noctiflora selected=~/gemoma/Mt_selected a=~/genomes/ncbi_dataset/data/GCF_003473485.1/genomic.gff g=~/genomes/ncbi_dataset/data/GCF_003473485.1/GCF_003473485.1_MtrunA17r5.0-ANR_genomic.fna GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_001925005.1/GCA_001925005.1_ASM192500v1_genomic.fna outdir=~/gemoma/Mt_Drosera_capensis selected=~/gemoma/Mt_selected a=~/genomes/ncbi_dataset/data/GCF_003473485.1/genomic.gff g=~/genomes/ncbi_dataset/data/GCF_003473485.1/GCF_003473485.1_MtrunA17r5.0-ANR_genomic.fna GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_018983105.1/GCA_018983105.1_ASM1898310v1_genomic.fna outdir=~/gemoma/Mt_Silene_uniflora selected=~/gemoma/Mt_selected a=~/genomes/ncbi_dataset/data/GCF_003473485.1/genomic.gff g=~/genomes/ncbi_dataset/data/GCF_003473485.1/GCF_003473485.1_MtrunA17r5.0-ANR_genomic.fna GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_029747015.1/GCA_029747015.1_UA_SGP5p_2_genomic.fna outdir=~/gemoma/Mt_Carnegiea_gigantea selected=~/gemoma/Mt_selected a=~/genomes/ncbi_dataset/data/GCF_003473485.1/genomic.gff g=~/genomes/ncbi_dataset/data/GCF_003473485.1/GCF_003473485.1_MtrunA17r5.0-ANR_genomic.fna GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_022085475.1/GCA_022085475.1_ASM2208547v1_genomic.fna outdir=~/gemoma/Mt_Heliosperma_pusillum selected=~/gemoma/Mt_selected a=~/genomes/ncbi_dataset/data/GCF_003473485.1/genomic.gff g=~/genomes/ncbi_dataset/data/GCF_003473485.1/GCF_003473485.1_MtrunA17r5.0-ANR_genomic.fna GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_028566215.1/GCA_028566215.1_ASM2856621v1_genomic.fna outdir=~/gemoma/Mt_Silene_coronaria selected=~/gemoma/Mt_selected a=~/genomes/ncbi_dataset/data/GCF_003473485.1/genomic.gff g=~/genomes/ncbi_dataset/data/GCF_003473485.1/GCF_003473485.1_MtrunA17r5.0-ANR_genomic.fna GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCF_002917755.1/GCF_002917755.1_EL10_1.0_genomic.fna outdir=~/gemoma/Mt_Beta_vulgaris_subsp._vulgaris selected=~/gemoma/Mt_selected a=~/genomes/ncbi_dataset/data/GCF_003473485.1/genomic.gff g=~/genomes/ncbi_dataset/data/GCF_003473485.1/GCF_003473485.1_MtrunA17r5.0-ANR_genomic.fna GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCF_002007265.1/GCF_002007265.1_ASM200726v1_genomic.fna outdir=~/gemoma/Mt_Spinacia_oleracea selected=~/gemoma/Mt_selected a=~/genomes/ncbi_dataset/data/GCF_003473485.1/genomic.gff g=~/genomes/ncbi_dataset/data/GCF_003473485.1/GCF_003473485.1_MtrunA17r5.0-ANR_genomic.fna GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_026545225.1/GCA_026545225.1_ASM2654522v1_genomic.fna outdir=~/gemoma/Mt_Cornus_controversa selected=~/gemoma/Mt_selected a=~/genomes/ncbi_dataset/data/GCF_003473485.1/genomic.gff g=~/genomes/ncbi_dataset/data/GCF_003473485.1/GCF_003473485.1_MtrunA17r5.0-ANR_genomic.fna GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_008638375.1/GCA_008638375.1_ASM863837v1_genomic.fna outdir=~/gemoma/Mt_Nyssa_sinensis selected=~/gemoma/Mt_selected a=~/genomes/ncbi_dataset/data/GCF_003473485.1/genomic.gff g=~/genomes/ncbi_dataset/data/GCF_003473485.1/GCF_003473485.1_MtrunA17r5.0-ANR_genomic.fna GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_013391885.1/GCA_013391885.1_HMA_r1.2_0_genomic.fna outdir=~/gemoma/Mt_Hydrangea_macrophylla selected=~/gemoma/Mt_selected a=~/genomes/ncbi_dataset/data/GCF_003473485.1/genomic.gff g=~/genomes/ncbi_dataset/data/GCF_003473485.1/GCF_003473485.1_MtrunA17r5.0-ANR_genomic.fna GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCF_030987335.1/GCF_030987335.1_ASM3098733v1_genomic.fna outdir=~/gemoma/Mt_Cornus_florida selected=~/gemoma/Mt_selected a=~/genomes/ncbi_dataset/data/GCF_003473485.1/genomic.gff g=~/genomes/ncbi_dataset/data/GCF_003473485.1/GCF_003473485.1_MtrunA17r5.0-ANR_genomic.fna GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_015680905.1/GCA_015680905.1_ASM1568090v1_genomic.fna outdir=~/gemoma/Mt_Coptis_chinensis selected=~/gemoma/Mt_selected a=~/genomes/ncbi_dataset/data/GCF_003473485.1/genomic.gff g=~/genomes/ncbi_dataset/data/GCF_003473485.1/GCF_003473485.1_MtrunA17r5.0-ANR_genomic.fna GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_002738505.1/GCA_002738505.1_Aquilegia_coerulea_v1_genomic.fna outdir=~/gemoma/Mt_Aquilegia_coerulea selected=~/gemoma/Mt_selected a=~/genomes/ncbi_dataset/data/GCF_003473485.1/genomic.gff g=~/genomes/ncbi_dataset/data/GCF_003473485.1/GCF_003473485.1_MtrunA17r5.0-ANR_genomic.fna GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_013358455.1/GCA_013358455.1_MaSuRCA_all.p2_genomic.fna outdir=~/gemoma/Mt_Thalictrum_thalictroides selected=~/gemoma/Mt_selected a=~/genomes/ncbi_dataset/data/GCF_003473485.1/genomic.gff g=~/genomes/ncbi_dataset/data/GCF_003473485.1/GCF_003473485.1_MtrunA17r5.0-ANR_genomic.fna GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_028566255.1/GCA_028566255.1_ASM2856625v1_genomic.fna outdir=~/gemoma/Mt_Geranium_maculatum selected=~/gemoma/Mt_selected a=~/genomes/ncbi_dataset/data/GCF_003473485.1/genomic.gff g=~/genomes/ncbi_dataset/data/GCF_003473485.1/GCF_003473485.1_MtrunA17r5.0-ANR_genomic.fna GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_900128785.1/GCA_900128785.1_MPIPZ.v5_genomic.fna outdir=~/gemoma/Mt_Arabis_alpina selected=~/gemoma/Mt_selected a=~/genomes/ncbi_dataset/data/GCF_003473485.1/genomic.gff g=~/genomes/ncbi_dataset/data/GCF_003473485.1/GCF_003473485.1_MtrunA17r5.0-ANR_genomic.fna GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_963576765.1/GCA_963576765.1_ddDraInca1.1_genomic.fna outdir=~/gemoma/Mt_Draba_incana selected=~/gemoma/Mt_selected a=~/genomes/ncbi_dataset/data/GCF_003473485.1/genomic.gff g=~/genomes/ncbi_dataset/data/GCF_003473485.1/GCF_003473485.1_MtrunA17r5.0-ANR_genomic.fna GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_001974645.1/GCA_001974645.1_C_bursa_pastoris_nuclear_genome_v1_genomic.fna outdir=~/gemoma/Mt_Capsella_bursa-pastoris selected=~/gemoma/Mt_selected a=~/genomes/ncbi_dataset/data/GCF_003473485.1/genomic.gff g=~/genomes/ncbi_dataset/data/GCF_003473485.1/GCF_003473485.1_MtrunA17r5.0-ANR_genomic.fna GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_020283515.1/GCA_020283515.1_Apet_EFCC3-3-20v4_genomic.fna outdir=~/gemoma/Mt_Alliaria_petiolata selected=~/gemoma/Mt_selected a=~/genomes/ncbi_dataset/data/GCF_003473485.1/genomic.gff g=~/genomes/ncbi_dataset/data/GCF_003473485.1/GCF_003473485.1_MtrunA17r5.0-ANR_genomic.fna GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_014578085.1/GCA_014578085.1_Cresedifolia_CH_v1_genomic.fna outdir=~/gemoma/Mt_Cardamine_resedifolia selected=~/gemoma/Mt_selected a=~/genomes/ncbi_dataset/data/GCF_003473485.1/genomic.gff g=~/genomes/ncbi_dataset/data/GCF_003473485.1/GCF_003473485.1_MtrunA17r5.0-ANR_genomic.fna GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_900406315.1/GCA_900406315.1_Biscutella longifolia_genomic.fna outdir=~/gemoma/Mt_Biscutella_laevigata_subsp._laevigata selected=~/gemoma/Mt_selected a=~/genomes/ncbi_dataset/data/GCF_003473485.1/genomic.gff g=~/genomes/ncbi_dataset/data/GCF_003473485.1/GCF_003473485.1_MtrunA17r5.0-ANR_genomic.fna GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_900406495.1/GCA_900406495.1_ASM90040649v1_genomic.fna outdir=~/gemoma/Mt_Sisymbrium_altissimum selected=~/gemoma/Mt_selected a=~/genomes/ncbi_dataset/data/GCF_003473485.1/genomic.gff g=~/genomes/ncbi_dataset/data/GCF_003473485.1/GCF_003473485.1_MtrunA17r5.0-ANR_genomic.fna GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCF_000001735.4/GCF_000001735.4_TAIR10.1_genomic.fna outdir=~/gemoma/Mt_Arabidopsis_thaliana selected=~/gemoma/Mt_selected a=~/genomes/ncbi_dataset/data/GCF_003473485.1/genomic.gff g=~/genomes/ncbi_dataset/data/GCF_003473485.1/GCF_003473485.1_MtrunA17r5.0-ANR_genomic.fna GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_916181665.1/GCA_916181665.1_Oat OT3098 v2_genomic.fna outdir=~/gemoma/Mt_Avena_sativa selected=~/gemoma/Mt_selected a=~/genomes/ncbi_dataset/data/GCF_003473485.1/genomic.gff g=~/genomes/ncbi_dataset/data/GCF_003473485.1/GCF_003473485.1_MtrunA17r5.0-ANR_genomic.fna GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCF_018294505.1/GCF_018294505.1_IWGSC CS RefSeq v2.1_genomic.fna outdir=~/gemoma/Mt_Triticum_aestivum selected=~/gemoma/Mt_selected a=~/genomes/ncbi_dataset/data/GCF_003473485.1/genomic.gff g=~/genomes/ncbi_dataset/data/GCF_003473485.1/GCF_003473485.1_MtrunA17r5.0-ANR_genomic.fna GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCF_904849725.1/GCF_904849725.1_MorexV3_pseudomolecules_assembly_genomic.fna outdir=~/gemoma/Mt_Hordeum_vulgare_subsp._vulgare selected=~/gemoma/Mt_selected a=~/genomes/ncbi_dataset/data/GCF_003473485.1/genomic.gff g=~/genomes/ncbi_dataset/data/GCF_003473485.1/GCF_003473485.1_MtrunA17r5.0-ANR_genomic.fna GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCF_019359855.1/GCF_019359855.1_MPB_Lper_Kyuss_1697_genomic.fna outdir=~/gemoma/Mt_Lolium_perenne selected=~/gemoma/Mt_selected a=~/genomes/ncbi_dataset/data/GCF_003473485.1/genomic.gff g=~/genomes/ncbi_dataset/data/GCF_003473485.1/GCF_003473485.1_MtrunA17r5.0-ANR_genomic.fna GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_028641055.1/GCA_028641055.1_Alomy_genome_v1_genomic.fna outdir=~/gemoma/Mt_Alopecurus_myosuroides selected=~/gemoma/Mt_selected a=~/genomes/ncbi_dataset/data/GCF_003473485.1/genomic.gff g=~/genomes/ncbi_dataset/data/GCF_003473485.1/GCF_003473485.1_MtrunA17r5.0-ANR_genomic.fna GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_026929855.1/GCA_026929855.1_FRR_PoAnn_1.0_genomic.fna outdir=~/gemoma/Mt_Poa_annua selected=~/gemoma/Mt_selected a=~/genomes/ncbi_dataset/data/GCF_003473485.1/genomic.gff g=~/genomes/ncbi_dataset/data/GCF_003473485.1/GCF_003473485.1_MtrunA17r5.0-ANR_genomic.fna GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_007115705.1/GCA_007115705.1_ASM711570v1_genomic.fna outdir=~/gemoma/Mt_Dactylis_glomerata selected=~/gemoma/Mt_selected a=~/genomes/ncbi_dataset/data/GCF_003473485.1/genomic.gff g=~/genomes/ncbi_dataset/data/GCF_003473485.1/GCF_003473485.1_MtrunA17r5.0-ANR_genomic.fna GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCF_002870075.4/GCF_002870075.4_Lsat_Salinas_v11_genomic.fna outdir=~/gemoma/Mt_Lactuca_sativa selected=~/gemoma/Mt_selected a=~/genomes/ncbi_dataset/data/GCF_003473485.1/genomic.gff g=~/genomes/ncbi_dataset/data/GCF_003473485.1/GCF_003473485.1_MtrunA17r5.0-ANR_genomic.fna GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCF_002127325.2/GCF_002127325.2_HanXRQr2.0-SUNRISE_genomic.fna outdir=~/gemoma/Mt_Helianthus_annuus selected=~/gemoma/Mt_selected a=~/genomes/ncbi_dataset/data/GCF_003473485.1/genomic.gff g=~/genomes/ncbi_dataset/data/GCF_003473485.1/GCF_003473485.1_MtrunA17r5.0-ANR_genomic.fna GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_023525715.1/GCA_023525715.1_ASM2352571v1_genomic.fna outdir=~/gemoma/Mt_Cichorium_intybus selected=~/gemoma/Mt_selected a=~/genomes/ncbi_dataset/data/GCF_003473485.1/genomic.gff g=~/genomes/ncbi_dataset/data/GCF_003473485.1/GCF_003473485.1_MtrunA17r5.0-ANR_genomic.fna GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_025667525.1/GCA_025667525.1_Gcor_v1_genomic.fna outdir=~/gemoma/Mt_Glebionis_coronaria selected=~/gemoma/Mt_selected a=~/genomes/ncbi_dataset/data/GCF_003473485.1/genomic.gff g=~/genomes/ncbi_dataset/data/GCF_003473485.1/GCF_003473485.1_MtrunA17r5.0-ANR_genomic.fna GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_022545495.1/GCA_022545495.1_ASM2254549v1_genomic.fna outdir=~/gemoma/Mt_Chrysanthemum_lavandulifolium selected=~/gemoma/Mt_selected a=~/genomes/ncbi_dataset/data/GCF_003473485.1/genomic.gff g=~/genomes/ncbi_dataset/data/GCF_003473485.1/GCF_003473485.1_MtrunA17r5.0-ANR_genomic.fna GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_014162995.1/GCA_014162995.1_Aran_genomic.fna outdir=~/gemoma/Mt_Artemisia_annua selected=~/gemoma/Mt_selected a=~/genomes/ncbi_dataset/data/GCF_003473485.1/genomic.gff g=~/genomes/ncbi_dataset/data/GCF_003473485.1/GCF_003473485.1_MtrunA17r5.0-ANR_genomic.fna GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_026074375.1/GCA_026074375.1_Tcoc_v1.0_genomic.fna outdir=~/gemoma/Mt_Tanacetum_coccineum selected=~/gemoma/Mt_selected a=~/genomes/ncbi_dataset/data/GCF_003473485.1/genomic.gff g=~/genomes/ncbi_dataset/data/GCF_003473485.1/GCF_003473485.1_MtrunA17r5.0-ANR_genomic.fna GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"
GeMoMa GeMoMaPipeline threads=12 GeMoMa.Score=ReAlign AnnotationFinalizer.r=NO o=true t=~/genomes/ncbi_dataset/data/GCA_910822075.1/GCA_910822075.1_dSenSqu2.1_genomic.fna outdir=~/gemoma/Mt_Senecio_squalidus selected=~/gemoma/Mt_selected a=~/genomes/ncbi_dataset/data/GCF_003473485.1/genomic.gff g=~/genomes/ncbi_dataset/data/GCF_003473485.1/GCF_003473485.1_MtrunA17r5.0-ANR_genomic.fna GAF.f="start=='M' and (isNaN(score) or score/aa>=0.75)"


#rename all "predicted_proteins.fasta" files within each folder using the bash script "rename_with_dir.sh". Try with echo first, the without if it looks good
cd $HOME/gemoma
bash rename_with_dir.sh

# #Bash script:
# # #!/bin/bash
# # shopt -s globstar  ##globstar will let us match files recursively
# # files=( /home/pers/juliana.almario/gemoma/**/predicted_proteins.fasta )  ##Array containing matched files, mention where to search and what files here
# # for i in "${files[@]}"; do 
# #     d="${i%/*}"  ##Parameter expansion, gets the path upto the parent directory
# #     d_="${d##*/}"  ##gets the name of parent directory
# #     f="${i##*/}"  ##gets the file namepw
# #        echo mv "$i" "$d"/"${d_}""_""$f"  ##renaming, remove echo after confirming what will be changed and you are good
# # done


#rename sequences with file name to add plant species and reference genome to fasta header, then concatenate all sequences in one file "All_predicted_proteins.fasta"
cd $HOME
find gemoma/ -name '*_predicted_proteins.fasta' -exec awk '/>/{sub(">",">"FILENAME"_");sub(/\.fasta/,x);sub(/gemoma\/.*\//,x)}1' {} + > All_predicted_proteins.fasta
mv All_predicted_proteins.fasta ~/gemoma

cd $HOME/gemoma

#Divide sequences by gene and reference genome
#Os reference
#str2
grep -A 1 "ref-gene=Os07t0191600-04.gene" All_predicted_proteins.fasta > str2_Os_predicted_proteins.fasta
#symrk
grep -A 1 "ref-gene=Os07t0568100-01.gene" All_predicted_proteins.fasta > symrk_Os_predicted_proteins.fasta
#ccamk
grep -A 1 "ref-gene=Os05t0489900-01.gene" All_predicted_proteins.fasta > ccamk_Os_predicted_proteins.fasta
#cyclops
grep -A 1 "ref-gene=Os06t0115600-01.gene" All_predicted_proteins.fasta > cyclops_Os_predicted_proteins.fasta

#Mt reference
#str2
grep -A 1 "ref-gene=gene-LOC11407838" All_predicted_proteins.fasta > str2_Mt_predicted_proteins.fasta
#symrk
grep -A 1 "ref-gene=gene-LOC11407326" All_predicted_proteins.fasta > symrk_Mt_predicted_proteins.fasta
#ccamk
grep -A 1 "ref-gene=gene-CCAMK" All_predicted_proteins.fasta > ccamk_Mt_predicted_proteins.fasta
#cyclops
grep -A 1 "ref-gene=gene-IPD3" All_predicted_proteins.fasta > cyclops_Mt_predicted_proteins.fasta

#Clean headers
awk '/^>/ {print $1;next}1' str2_Os_predicted_proteins.fasta > clean_str2_Os_predicted_proteins.fasta
awk '/^>/ {print $1;next}1' symrk_Os_predicted_proteins.fasta > clean_symrk_Os_predicted_proteins.fasta
awk '/^>/ {print $1;next}1' ccamk_Os_predicted_proteins.fasta > clean_ccamk_Os_predicted_proteins.fasta
awk '/^>/ {print $1;next}1' cyclops_Os_predicted_proteins.fasta > clean_cyclops_Os_predicted_proteins.fasta

awk '/^>/ {print $1;next}1' str2_Mt_predicted_proteins.fasta > clean_str2_Mt_predicted_proteins.fasta
awk '/^>/ {print $1;next}1' symrk_Mt_predicted_proteins.fasta > clean_symrk_Mt_predicted_proteins.fasta
awk '/^>/ {print $1;next}1' ccamk_Mt_predicted_proteins.fasta > clean_ccamk_Mt_predicted_proteins.fasta
awk '/^>/ {print $1;next}1' cyclops_Mt_predicted_proteins.fasta > clean_cyclops_Mt_predicted_proteins.fasta

#Specific for Geranium maculatum STR2:no predicted protein starting with M and having a high score. Here we collect the prediction with the higher score, with a stop, which is the most similar to Medicago's STR2. It starts with N.
conda activate gemoma
cd gemoma/Mt_Geranium_maculatum/
#extract matching sequences (high score) starting with M but NOT finishig with a stop codon 
GeMoMa GAF g=unfiltered_predictions_from_species_0.gff f="start=='N' and (isNaN(score) or score/aa>=0.75)"
GeMoMa Extractor g=~/genomes/ncbi_dataset/data/GCA_028566255.1/GCA_028566255.1_ASM2856625v1_genomic.fna a=filtered_predictions.gff p=true sefc=true
#Rename this sequence and create a new file. Later append it to the file STR2.fa before alignement
sed 's/>/>Mt_Geranium_maculatum_/' proteins.fasta > Mt_Gm_STR2_proteins.fasta
#move the file to the main directory
mv Mt_Gm_STR2_proteins.fasta $HOME/gemoma/


#to work in itol we need the list of sequences ids to create the annotation files, get them using the seqkit package
#install seqkit
conda create -n seqkit
conda activate seqkit
conda install -c bioconda seqkit
conda activate seqkit
#get seq ids as tab file first with echo to be sure, the without
for i in clean* ; do echo seqkit seq -n $i -o ${i%%\.fasta}_tab.fa;done
for i in clean_*.fasta ; do seqkit seq -n $i -o ${i%%\.fasta}_tab.fa;done

# #copy to your local disk
rsync -avzh juliana.almario@ibio:~/gemoma/clean* /Users/julianaalmario/Documents/Labo/Projets/2019_EC2Co_Orchamp/Primers_STR/Sym_genes_genoms/


#Align the sequences with muscle(default param) and make the tree with iqtree
#Install muscle
conda create -n muscle
conda activate muscle
conda install -c bioconda muscle

#Install iqtree
conda create -n iqtree
conda activate iqtree
conda install -c bioconda iqtree

cd $HOME/gemoma

#STR2
cat "clean_str2_Os_predicted_proteins.fasta" "clean_str2_Mt_predicted_proteins.fasta" "STR2_refseqs_181023.txt" "Mt_Gm_STR2_proteins.fasta" > "STR2.fa"
conda activate muscle
muscle -align STR2.fa -output STR2.afa
conda activate iqtree
iqtree -nt 12 -s STR2.afa -B 1000 -alrt 1000 -redo

#CCAMK
cat "clean_ccamk_Os_predicted_proteins.fasta" "clean_ccamk_Mt_predicted_proteins.fasta" "CCAMK_refseqs_201223.txt" > "CCAMK.fa"
conda activate muscle
muscle -align CCAMK.fa -output CCAMK.afa
conda activate iqtree
iqtree -nt 12 -s CCAMK.afa -B 1000 -alrt 1000

#SYMRK
cat "clean_symrk_Os_predicted_proteins.fasta" "clean_symrk_Mt_predicted_proteins.fasta" "SYMRK_refseqs_201223.txt" "Mt_Ps_SYMRK_proteins.fasta" "Mt_Pa_SYMRK_proteins.fasta" > "SYMRK.fa"
conda activate muscle
muscle -align SYMRK.fa -output SYMRK.afa
conda activate iqtree
iqtree -nt 12 -s SYMRK.afa -B 1000 -alrt 1000 -redo


#CYCLOPS
cat "clean_cyclops_Os_predicted_proteins.fasta" "clean_cyclops_Mt_predicted_proteins.fasta" "CYCLOPS_refseqs_201223.txt" > "CYCLOPS.fa"
conda activate muscle
muscle -align CYCLOPS.fa -output CYCLOPS.afa
conda activate iqtree
iqtree -nt 12 -s CYCLOPS.afa -B 1000 -alrt 1000
